services:
  flask_app:
    build: .
    container_name: floodrisk-service
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - gis_network

networks:
  gis_network:
    driver: bridge
    name: analyst_network